<?php
/*
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Entity;

/**
 * This file has been generated by the Sonata product generation command ( http://sonata-project.org/ )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author Lander Vanderstraeten <lander.vanderstraeten@hotmail.com>
 */
class Shoe extends Product
{
    const SIZE_41 = '41';
    const SIZE_42 = '42';
    const SIZE_43 = '43';

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $size
     */
    protected $size;

    /**
     * @param int $color
     */
    public function setSize($color)
    {
        $this->size = $color;
    }

    /**
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return array
     */
    public static function getSizesList()
    {
        return array(
            static::SIZE_41 => static::SIZE_41,
            static::SIZE_42 => static::SIZE_42,
            static::SIZE_43 => static::SIZE_43,
        );
    }
}
