<?php
/*
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Entity;

/**
 * This file has been generated by the Sonata product generation command ( http://sonata-project.org/ )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author Lander Vanderstraeten <lander.vanderstraeten@hotmail.com>
 */
class Shoe extends Product
{
    const COLOR_BLACK = 'Black';
    const COLOR_BLUE = 'Blue';
    const COLOR_RED = 'Red';

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var integer $size
     */
    protected $color;

    /**
     * @param int $color
     */
    public function setColor($color)
    {
        $this->color = $color;
    }

    /**
     * @return int
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return array
     */
    public static function getColorList()
    {
        return array(
            static::COLOR_BLACK => static::COLOR_BLACK,
            static::COLOR_BLUE => static::COLOR_BLUE,
            static::COLOR_RED => static::COLOR_RED,
        );
    }
}
