services:
    sonata.clothing_store.product.shoe.manager:
        class: Sonata\ProductBundle\Entity\ProductManager
        arguments:
            - Application\Sonata\ProductBundle\Entity\Shoe
            - @doctrine

    sonata.clothing_store.product.shoe.type:
        class: Application\Sonata\ProductBundle\Provider\ShoeProductProvider
        arguments:
            - @serializer
