<?php
/*
 * This file is part of the sonata project.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Provider;

use Sonata\AdminBundle\Form\FormMapper;
use Application\Sonata\ProductBundle\Entity\Shoe;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   custom repository : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en#querying:custom-repositories
 *   query builder     : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/query-builder/en
 *   dql               : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/dql-doctrine-query-language/en
 *
 * @author Lander Vanderstraeten <lander.vanderstraeten@hotmail.com>
 */
class ShoeProductProvider extends ProductProvider
{
    /**
     * {@inheritDoc}
     */
    public function getBaseControllerName()
    {
        return 'SonataProductBundle:Shoe';
    }

    public function buildEditForm(FormMapper $formMapper, $isVariation = false)
    {
        parent::buildEditForm($formMapper, $isVariation);

        if ($isVariation) {
            $formMapper->with('Product')
                ->add(
                    'size',
                    'choice',
                    array(
                        'choices' => Shoe::getSizesList(),
                        'translation_domain' => 'ApplicationSonataProductBundle',
                    )
                )
                ->end();
        }
    }
}
